In [1]:
import pandas as pd
import numpy as np
# For visualizations
import matplotlib.pyplot as plt
import scipy
import re
# For handling string
import string
# For performing mathematical operations
import math
import nltk 

%matplotlib inline

In [8]:
df = pd.read_csv("C:/Users/John/Documents/MMA/Big Data/Assignments/Individual/sentiment_train.csv")
df.head(5)

Sentence  Polarity
0                           Wow... Loved this place.         1
1                                 Crust is not good.         0
2          Not tasty and the texture was just nasty.         0
3  Stopped by during the late May bank holiday of...         1
4  The selection on the menu was great and so wer...         1

In [9]:
df["no_punct"] = df['Sentence'].str.replace('[^\w\s]','')
df.head(n=20)

Sentence  Polarity  \
0                            Wow... Loved this place.         1   
1                                  Crust is not good.         0   
2           Not tasty and the texture was just nasty.         0   
3   Stopped by during the late May bank holiday of...         1   
4   The selection on the menu was great and so wer...         1   
5      Now I am getting angry and I want my damn pho.         0   
6               Honeslty it didn't taste THAT fresh.)         0   
7   The potatoes were like rubber and you could te...         0   
8                           The fries were great too.         1   
9                                      A great touch.         1   
10                           Service was very prompt.         1   
11                                 Would not go back.         0   
12  The cashier had no care what so ever on what I...         0   
13  I tried the Cape Cod ravoli, chicken,with cran...         1   
14  I was disgusted because I was pretty sure that...         0   
15  I was shocked because no signs indicate cash o...         0   
16                                Highly recommended.         1   
17             Waitress was a little slow in service.         0   
18  This place is not worth your time, let alone V...         0   
19                               did not like at all.         0   

                                             no_punct  
0                                Wow Loved this place  
1                                   Crust is not good  
2            Not tasty and the texture was just nasty  
3   Stopped by during the late May bank holiday of...  
4   The selection on the menu was great and so wer...  
5       Now I am getting angry and I want my damn pho  
6                  Honeslty it didnt taste THAT fresh  
7   The potatoes were like rubber and you could te...  
8                            The fries were great too  
9                                       A great touch  
10                            Service was very prompt  
11                                  Would not go back  
12  The cashier had no care what so ever on what I...  
13  I tried the Cape Cod ravoli chickenwith cranbe...  
14  I was disgusted because I was pretty sure that...  
15  I was shocked because no signs indicate cash only  
16                                 Highly recommended  
17              Waitress was a little slow in service  
18  This place is not worth your time let alone Vegas  
19                                did not like at all

In [10]:
df['lowered_text']=df['no_punct'].apply(lambda x: x.lower())
df.head()

Sentence  Polarity  \
0                           Wow... Loved this place.         1   
1                                 Crust is not good.         0   
2          Not tasty and the texture was just nasty.         0   
3  Stopped by during the late May bank holiday of...         1   
4  The selection on the menu was great and so wer...         1   

                                            no_punct  \
0                               Wow Loved this place   
1                                  Crust is not good   
2           Not tasty and the texture was just nasty   
3  Stopped by during the late May bank holiday of...   
4  The selection on the menu was great and so wer...   

                                        lowered_text  
0                               wow loved this place  
1                                  crust is not good  
2           not tasty and the texture was just nasty  
3  stopped by during the late may bank holiday of...  
4  the selection on the menu was great and so wer...

In [11]:
from nltk.corpus import stopwords
nltk.download('stopwords')
stop = stopwords.words('english')
df['StopwordsCount'] = df['lowered_text']
df['StopwordsCount'] = df['StopwordsCount'].apply(lambda x: len([x for x in x.split() if x in stop]))
df.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\John\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


Sentence  Polarity  \
0                           Wow... Loved this place.         1   
1                                 Crust is not good.         0   
2          Not tasty and the texture was just nasty.         0   
3  Stopped by during the late May bank holiday of...         1   
4  The selection on the menu was great and so wer...         1   

                                            no_punct  \
0                               Wow Loved this place   
1                                  Crust is not good   
2           Not tasty and the texture was just nasty   
3  Stopped by during the late May bank holiday of...   
4  The selection on the menu was great and so wer...   

                                        lowered_text  StopwordsCount  
0                               wow loved this place               1  
1                                  crust is not good               2  
2           not tasty and the texture was just nasty               5  
3  stopped by during the late may bank holiday of...               6  
4  the selection on the menu was great and so wer...               8

In [12]:
df['reviewTextnoStop'] = df['lowered_text'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
df.head(5)

Sentence  Polarity  \
0                           Wow... Loved this place.         1   
1                                 Crust is not good.         0   
2          Not tasty and the texture was just nasty.         0   
3  Stopped by during the late May bank holiday of...         1   
4  The selection on the menu was great and so wer...         1   

                                            no_punct  \
0                               Wow Loved this place   
1                                  Crust is not good   
2           Not tasty and the texture was just nasty   
3  Stopped by during the late May bank holiday of...   
4  The selection on the menu was great and so wer...   

                                        lowered_text  StopwordsCount  \
0                               wow loved this place               1   
1                                  crust is not good               2   
2           not tasty and the texture was just nasty               5   
3  stopped by during the late may bank holiday of...               6   
4  the selection on the menu was great and so wer...               8   

                                    reviewTextnoStop  
0                                    wow loved place  
1                                         crust good  
2                                tasty texture nasty  
3  stopped late may bank holiday rick steve recom...  
4                        selection menu great prices

In [13]:
df.shape

(2202, 6)

In [14]:
#Word Count
df['word_count'] = df['no_punct'].apply(lambda x: len(str(x).split(" ")))
df[['no_punct','word_count']].head()

no_punct  word_count
0                               Wow Loved this place           4
1                                  Crust is not good           4
2           Not tasty and the texture was just nasty           8
3  Stopped by during the late May bank holiday of...          15
4  The selection on the menu was great and so wer...          12

In [15]:
df['non_stop_count'] = df['word_count'] - df['StopwordsCount']
df.head(5)

Sentence  Polarity  \
0                           Wow... Loved this place.         1   
1                                 Crust is not good.         0   
2          Not tasty and the texture was just nasty.         0   
3  Stopped by during the late May bank holiday of...         1   
4  The selection on the menu was great and so wer...         1   

                                            no_punct  \
0                               Wow Loved this place   
1                                  Crust is not good   
2           Not tasty and the texture was just nasty   
3  Stopped by during the late May bank holiday of...   
4  The selection on the menu was great and so wer...   

                                        lowered_text  StopwordsCount  \
0                               wow loved this place               1   
1                                  crust is not good               2   
2           not tasty and the texture was just nasty               5   
3  stopped by during the late may bank holiday of...               6   
4  the selection on the menu was great and so wer...               8   

                                    reviewTextnoStop  word_count  \
0                                    wow loved place           4   
1                                         crust good           4   
2                                tasty texture nasty           8   
3  stopped late may bank holiday rick steve recom...          15   
4                        selection menu great prices          12   

   non_stop_count  
0               3  
1               2  
2               3  
3               9  
4               4

In [ ]:
#remove Numerics?????

In [20]:
#Commonly occuring words
#freq = pd.Series(' '.join(df['reviewTextnoStop']).split()).value_counts()[:8]
#freq

good       192
great      181
phone      162
food       123
place      110
1          110
service    106
0          100
dtype: int64

In [22]:

#freq = list(freq)
#df['reviewTextnoStop'] = df['reviewTextnoStop'].apply(lambda x: " ".join(x for x in x.split() if x not in freq))
#df['reviewTextnoStop'].head()

0                                      wow loved place
1                                           crust good
2                                  tasty texture nasty
3    stopped late may bank holiday rick steve recom...
4                          selection menu great prices
Name: reviewTextnoStop, dtype: object

In [27]:
#Count of rare words
#freq_rare = pd.Series(' '.join(df['reviewTextnoStop']).split()).value_counts()[-500:]
#freq_rare

create          1
welldesigned    1
venture         1
insults         1
negligent       1
               ..
wires           1
rubber          1
loads           1
pub             1
itll            1
Length: 500, dtype: int64

In [ ]:
#removal of rarely occuring irrelevant words

#freq_rare = list(freq_rare)
#df['reviewTextnoStop'] = df['reviewTextnoStop'].apply(lambda x: " ".join(x for x in x.split() if x not in freq))
#df['reviewTextnoStop'].head()

In [35]:
from textblob import TextBlob
import nltk
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\John\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [38]:
TextBlob(df['reviewTextnoStop'][100]).word_counts

defaultdict(int,
            {'server': 1,
             'fantastic': 1,
             'found': 1,
             'wife': 1,
             'loves': 1,
             'roasted': 1,
             'garlic': 1,
             'bone': 1,
             'marrow': 2,
             'added': 1,
             'extra': 1,
             'meal': 1,
             'another': 1,
             'go': 1})

In [41]:
from textblob import Word
nltk.download('wordnet')
df['reviewTextnoStop'] = df['reviewTextnoStop'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))
df['reviewTextnoStop'].head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\John\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


0                                      wow loved place
1                                           crust good
2                                  tasty texture nasty
3    stopped late may bank holiday rick steve recom...
4                           selection menu great price
Name: reviewTextnoStop, dtype: object

In [42]:
TextBlob(df['reviewTextnoStop'][0]).ngrams(4)

[]

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [44]:
vec_idf=TfidfVectorizer()

In [45]:
w=vec_idf.fit(df['reviewTextnoStop'])

In [46]:
vec_idf.vocabulary_

{'wow': 3664,
 'loved': 1909,
 'place': 2378,
 'crust': 794,
 'good': 1406,
 'tasty': 3219,
 'texture': 3243,
 'nasty': 2114,
 'stopped': 3095,
 'late': 1806,
 'may': 1977,
 'bank': 282,
 'holiday': 1553,
 'rick': 2705,
 'steve': 3086,
 'recommendation': 2613,
 'selection': 2838,
 'menu': 2010,
 'great': 1426,
 'price': 2471,
 'getting': 1379,
 'angry': 161,
 'want': 3544,
 'damn': 820,
 'pho': 2352,
 'honeslty': 1558,
 'didnt': 900,
 'taste': 3215,
 'fresh': 1327,
 'potato': 2440,
 'like': 1853,
 'rubber': 2742,
 'could': 747,
 'tell': 3232,
 'made': 1927,
 'ahead': 117,
 'time': 3292,
 'kept': 1765,
 'warmer': 3548,
 'fry': 1338,
 'touch': 3327,
 'service': 2862,
 'prompt': 2495,
 'would': 3659,
 'go': 1395,
 'back': 268,
 'cashier': 526,
 'care': 511,
 'ever': 1119,
 'say': 2791,
 'still': 3088,
 'ended': 1081,
 'wayyy': 3567,
 'overpriced': 2255,
 'tried': 3361,
 'cape': 505,
 'cod': 638,
 'ravoli': 2573,
 'chickenwith': 588,
 'cranberrymmmm': 769,
 'disgusted': 936,
 'pretty': 246

In [47]:
z=w.transform(df['reviewTextnoStop'])

In [48]:
print(z.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
